version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_form_builder
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_form_builder
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_form_builder
    volumes:
      - ./Frontend:/app
    ports:
      - "5173:5173"

volumes:
  postgres_data:
